### ISSUE TITLE
Entry point error

### ISSUE THREAD

**Issue by tochimclaren** [testdrivenio/django-on-docker#61]
When I run docker compose I get this error

`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/src/app/entrypoint.sh": permission denied: unknown
`

# Docker file

`FROM python:3.11.4-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

COPY . .

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]`

**Comment by tochimclaren** [comment]
The cause of this was permission problem `entrypoint.sh` it's better to set the permission in the code before copying it because for some reason this line `RUN chmod +x /usr/src/app/entrypoint.sh` does not work.

**Comment by ghost** [comment]
You can also use `COPY --chmod=755 ./entrypoint.sh .` to avoid `RUN chmod +x /usr/src/app/entrypoint.sh`, but they both don't work because the bind mount in docker compose overrides this folder including this entrypoint. 

I would avoid all the lines below since you already do a `COPY . .` ? Not sure why you need the `sed` command. Maybe when you are on Windows?
```
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh
```
Instead of adding execute permissions on that file I just run it like this:
```
ENTRYPOINT ["/bin/bash", "/usr/src/app/entrypoint.sh"]
```
